# Generated by Django 5.1 on 2024-08-18 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_completed_alter_task_due_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='due_by',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 13, 33, 37, 703337)),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
