# Generated by Django 5.1 on 2024-08-18 12:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_user_alter_task_due_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_by',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 13, 36, 56, 773226)),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
