# Generated by Django 5.1 on 2024-08-18 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_due_by_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_by',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 13, 37, 53, 618858)),
        ),
    ]
